### ISSUE TITLE
Ability to hide blacklisted galleries on nhentai

### ISSUE THREAD

**Issue by blockall** [avluis/Hentoid#722]
My problem:
I have a lot of blacklisted tags on nhentai and because of that I see a lot of pages with only 2-3 galleries and waste time scrolling. On the computer I use Stylish addon with the following css to hide blacklisted one:

```css
.blacklisted.gallery {
    display: none !important;
}
```

Would be nice if something similar was possible inside Hentoid (as a ability to use custom css for site or one config option to hide blacklisted galleries - on tsumino I can use bookmark to hide them).
